apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
spec:
  selector:
    matchLabels:
      app: pipeline
  replicas: 1
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
        - name: pipeline
          image: rochanahuel/newpipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 8090


---

apiVersion: v1
kind: Service
metadata:
  name: pipeline-ssvc
spec:
  selector:
    app: pipeline
  ports:
    - protocol: "TCP"
      port: 8090
      targetPort: 8090
  type: NodePort